#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.
# See the NOTICE file distributed with this work for additional information regarding copyright
# ownership. The ASF licenses this file to you under the Apache License, Version 2.0.
#
# Pod-side pull for `waged-sim setup --from pensieve`. Runs Pensieve (the ZooKeeper point-in-time
# viewer) inside a ZooKeeper backup pod and writes one text file per znode tree into a folder,
# then tars it. Read-only: it reads backup snapshots and transaction logs, nothing else.
# Generated by: waged-sim pensieve-script --cluster @CLUSTER@ --time '@TIME@'
set -u
CLUSTER='@CLUSTER@'
TIME='@TIME@'
BACKUP_DIR='@BACKUP_DIR@'
JAR='@JAR@'
JAVA='@JAVA@'
OUT="/tmp/waged-sim-pull/${CLUSTER}"
INCLUDE_INSTANCES="${INCLUDE_INSTANCES:-0}"

rm -rf "$OUT"; mkdir -p "$OUT"
cd /tmp || exit 1
run() { nice -n 10 "$JAVA" -Xmx2g -Duser.timezone=UTC -jar "$JAR" -s "$BACKUP_DIR" -l "$BACKUP_DIR" -t "$TIME" "$@" 2>/dev/null; }

echo "pull $CLUSTER at $TIME -> $OUT"
for TREE in CONFIGS LIVEINSTANCES STATEMODELDEFS IDEALSTATES EXTERNALVIEW; do
  run -p "/$CLUSTER/$TREE" -r > "$OUT/$TREE.txt"
  echo "  $TREE $(wc -c < "$OUT/$TREE.txt") bytes"
done
run -p "/$CLUSTER/CONTROLLER/LEADER" > "$OUT/CONTROLLER_LEADER.txt"

for KIND in BASELINE BEST_POSSIBLE; do
  run -p "/$CLUSTER/ASSIGNMENT_METADATA/$KIND/LAST_SUCCESSFUL_WRITE" > "$OUT/${KIND}__lsw.txt"
  V=$(grep -A1 '^Data (' "$OUT/${KIND}__lsw.txt" | tail -1 | tr -dc '0-9')
  if [ -z "$V" ]; then echo "  $KIND: no version"; continue; fi
  run -p "/$CLUSTER/ASSIGNMENT_METADATA/$KIND/$V" -r > "$OUT/${KIND}__tree.txt"
  DS=$(grep -o 'DATA_SIZE[^0-9]*[0-9][0-9]*' "$OUT/${KIND}__tree.txt" | grep -o '[0-9][0-9]*$' | head -1)
  BS=$(grep -o 'BUCKET_SIZE[^0-9]*[0-9][0-9]*' "$OUT/${KIND}__tree.txt" | grep -o '[0-9][0-9]*$' | head -1)
  [ -z "$DS" ] && DS=0; [ -z "$BS" ] && BS=51200
  NB=$(( (DS + BS - 1) / BS )); [ "$NB" -lt 1 ] && NB=1
  i=0
  while [ "$i" -lt "$NB" ]; do
    run -p "/$CLUSTER/ASSIGNMENT_METADATA/$KIND/$V/$i" > "$OUT/${KIND}__b${i}.txt"
    i=$((i + 1))
  done
  echo "  $KIND version $V, $DS bytes, $NB buckets"
done

if [ "$INCLUDE_INSTANCES" = "1" ]; then
  # Participant history and current states. This tree also holds status updates and can be large.
  run -p "/$CLUSTER/INSTANCES" -r > "$OUT/INSTANCES.txt"
  echo "  INSTANCES $(wc -c < "$OUT/INSTANCES.txt") bytes"
fi

rm -f /tmp/zk-point-in-time-viewer.log
tar czf "/tmp/waged-sim-pull-${CLUSTER}.tgz" -C /tmp/waged-sim-pull "$CLUSTER"
echo "DONE /tmp/waged-sim-pull-${CLUSTER}.tgz"
